name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
    paths:
      - 'build/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important if you need the full history for build scripts
          
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: "none"  # Explicitly set since you're deploying pre-built files
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'  # Explicitly target the build directory
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
