name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
    paths:
      - 'build/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Debug: Verify build directory exists
      - name: List files
        run: |
          ls -la
          ls -la build/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          keep_files: false  # Clean existing files before deploy
          force_orphan: true  # Single commit in gh-pages branch
